extmod/moduselect: Fix sign-compare compile error
error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

Use UINT_MAX instead of -1.